// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import { JsonResult, Guid } from "./interface/index.ts";
import axios, { AxiosResponse } from "axios";

// 新增或编辑标准票, 需走审批流程
export const AddOrUpdateTicketTypical = () =>
  axios.request<JsonResult<Guid>, AxiosResponse<JsonResult<Guid>>>({
    url: `/api/services/app/YmTicketTypical/AddOrUpdateTicketTypical`,
    method: "post",
    params: {},
    data: {}
  });
