/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Swagger Petstore
 * @description This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 * @version 1.0.3
}
**/

/**
 * @typedef Category
 * @property {number} id
 * @property {string} name
**/

/**
 * @typedef Pet
 * @property {number} id
 * @property {Category} category
 * @property {string} name
 * @property {string[]} photoUrls
 * @property {Tag[]} tags
 * @property {"available" | "pending" | "sold"} status - pet status in the store
**/

/**
 * @typedef Tag
 * @property {number} id
 * @property {string} name
**/

/**
 * @typedef ApiResponse
 * @property {number} code
 * @property {string} type
 * @property {string} message
**/

/**
 * @typedef Order
 * @property {number} id
 * @property {number} petId
 * @property {number} quantity
 * @property {string} shipDate
 * @property {"placed" | "approved" | "delivered"} status - Order Status
 * @property {boolean} complete
**/

/**
 * @typedef User
 * @property {number} id
 * @property {string} username
 * @property {string} firstName
 * @property {string} lastName
 * @property {string} email
 * @property {string} password
 * @property {string} phone
 * @property {number} userStatus - User Status
**/