import { OpenAPIV2 } from 'openapi-types'
// 不要缩写，否则会找不到 map/genericInterfaceMap/recursiveMap
import {
  buildInInterfaces,
  genericInterfaceMap,
  map,
  recursiveMap,
  findInterface,
  parseInterface,
  resetInterfaceMap,
  shouldSkipGenerate,
} from '../parse/interface'
import { formatCode } from '../utils'
import { genInterface } from '../gen/interface'

// 生成单个 interface 代码
const compileInterface = (
  source: OpenAPIV2.Document,
  interfaceName: string,
  propComment?: string,
  noContext = false
): string => {
  if (!source.definitions || shouldSkipGenerate(interfaceName, noContext))
    return ''
  parseInterface(source.definitions, interfaceName)

  try {
    return formatCode('ts')(
      genInterface(findInterface(interfaceName), propComment)
    )
  } catch (e) {
    console.warn(
      `interfaceName: ${interfaceName} 生成失败，检查是否符合 swagger 规范`
    )
    console.warn(e)
    return `
    // interfaceName: ${interfaceName} 生成失败，检查是否符合 swagger 规范
    
    `
  }
}

// 生成全量 interface 代码
const compileInterfaces = (
  source: OpenAPIV2.Document,
  interfaceName?: string,
  propComment?: string
): string => {
  if (!source.definitions) return ''
  resetInterfaceMap()

  if (interfaceName) {
    return compileInterface(source, interfaceName, propComment, true)
  } else {
    const headerCode = `/* eslint-disable */
    // @ts-nocheck
    // generated by free-swagger-client
    
    `
    const buildInInterfaceCode = Object.keys(buildInInterfaces).reduce(
      (acc, cur) => acc + buildInInterfaces[cur].code,
      ''
    )

    Object.keys(source.definitions).forEach((key) => {
      parseInterface(source.definitions!, key)
    })

    const interfaceCode = Object.keys(map).reduce(
      (acc, cur) => acc + compileInterface(source, cur, propComment),
      ''
    )

    const recursiveInterfaceCode = Object.keys(recursiveMap).reduce(
      (acc, cur) =>
        acc + formatCode('ts')(genInterface(recursiveMap[cur], propComment)),
      ''
    )

    const interfaceWithGenericCode = Object.keys(genericInterfaceMap).reduce(
      (acc, cur) =>
        acc +
        formatCode('ts')(genInterface(genericInterfaceMap[cur], propComment)),
      ''
    )

    return formatCode('ts')(
      headerCode +
        buildInInterfaceCode +
        interfaceWithGenericCode +
        interfaceCode +
        recursiveInterfaceCode
    )
  }
}

export { compileInterface, compileInterfaces }
