/* eslint-disable */
// generated by free-swagger

import axios from "axios";
/**
 * @description Returns pet inventories by status  **/

// Returns pet inventories by status
export const getInventory = () =>
  axios.request({
    url: `/v2/store/inventory`,
    method: "get",
    params: {},
    data: {}
  });
/**
 * @description Find purchase order by ID
 * @param {Object} params -never
 * @param {Object} pathParams
 * @param {number} pathParams.orderId -ID of pet that needs to be fetched
 **/

// Find purchase order by ID
export const getOrderById = (params, { orderId }) =>
  axios.request({
    url: `/v2/store/order/${orderId}`,
    method: "get",
    params: {},
    data: {}
  });
/**
 * @description Delete purchase order by ID
 * @param {Object} params -never
 * @param {Object} pathParams
 * @param {number} pathParams.orderId -ID of the order that needs to be deleted
 **/

// Delete purchase order by ID
export const deleteOrder = (params, { orderId }) =>
  axios.request({
    url: `/v2/store/order/${orderId}`,
    method: "delete",
    params: {},
    data: {}
  });
/**
 * @description Place an order for a pet
 * @param {Order} params -order placed for purchasing the pet
 **/

// Place an order for a pet
export const placeOrder = (params) =>
  axios.request({
    url: `/v2/store/order`,
    method: "post",
    params: {},
    data: params
  });
