/* eslint-disable */
// @ts-nocheck
// generated by free-swagger

import axios, { AxiosResponse } from "axios";

export const UpdateMapper = (
  _NOOP: { [key: string]: never },
  {
    id
  }: {
    id: string;
  }
) =>
  axios.request<string, AxiosResponse<string>>({
    url: `/v1/crawler/v1/mapper/${id}`,
    method: "put",
    params: {},
    data: {}
  });
