/* eslint-disable */
// @ts-nocheck
// generated by free-swagger

import { AxiosResponse } from "axios";
import http from "http";

export const getZones = () =>
  http.request<string[], AxiosResponse<string[]>>({
    url: `/zones`,
    method: "get",
    params: {},
    data: {}
  });

export const quietZone = (
  params: { [key: string]: never },
  {
    zoneId
  }: {
    zoneId: string;
  }
) =>
  http.request<any, AxiosResponse<any>>({
    url: `/zones/${zoneId}/quiet`,
    method: "get",
    params: {},
    data: {}
  });
