// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import http, { AxiosResponse } from "axios";

export const getZones = () =>
  http.request<string[], AxiosResponse<string[]>>({
    url: `/zones`,
    method: "get",
    params: params,
    data: {}
  });

export const quietZone = (
  params: { [key: string]: never },
  { zoneId } = {
    zoneId: string
  }
) =>
  http.request<any, AxiosResponse<any>>({
    url: `/zones/${zoneId}/quiet`,
    method: "get",
    params: params,
    data: {}
  });
