/* eslint-disable */
// @ts-nocheck
// generated by free-swagger

import { ApiResponse, DeviceState, LightingSummary } from "./interface/index.ts";
import { AxiosResponse } from "axios";
import http from "http";

export const setDimmer = (
  params: { [key: string]: never },
  {
    deviceId,
    value
  }: {
    deviceId: string;
    value: number;
  }
) =>
  http.request<ApiResponse, AxiosResponse<ApiResponse>>({
    url: `/yeyan1996/IOT/1.0.0/lighting/dimmers/${deviceId}/${value}`,
    method: "post",
    params: {},
    data: {}
  });

export const setDimmerTimer = (
  params: {
    units?: string;
  },
  {
    deviceId,
    value,
    timeunit
  }: {
    deviceId: string;
    value: number;
    timeunit: number;
  }
) =>
  http.request<ApiResponse, AxiosResponse<ApiResponse>>({
    url: `/yeyan1996/IOT/1.0.0/lighting/dimmers/${deviceId}/${value}/timer/${timeunit}`,
    method: "post",
    params: params,
    data: {}
  });

export const getSwitchState = (
  params: { [key: string]: never },
  {
    deviceId
  }: {
    deviceId: string;
  }
) =>
  http.request<DeviceState, AxiosResponse<DeviceState>>({
    url: `/yeyan1996/IOT/1.0.0/lighting/switches/${deviceId}`,
    method: "get",
    params: {},
    data: {}
  });

export const setSwitch = (
  params: { [key: string]: never },
  {
    deviceId,
    value
  }: {
    deviceId: string;
    value: string;
  }
) =>
  http.request<ApiResponse, AxiosResponse<ApiResponse>>({
    url: `/yeyan1996/IOT/1.0.0/lighting/switches/${deviceId}/${value}`,
    method: "post",
    params: {},
    data: {}
  });

export const setSwitchTimer = (
  params: { [key: string]: never },
  {
    deviceId,
    value,
    minutes
  }: {
    deviceId: string;
    value: string;
    minutes: number;
  }
) =>
  http.request<ApiResponse, AxiosResponse<ApiResponse>>({
    url: `/yeyan1996/IOT/1.0.0/lighting/switches/${deviceId}/${value}/timer/${minutes}`,
    method: "post",
    params: {},
    data: {}
  });

export const getLightingSummary = () =>
  http.request<LightingSummary, AxiosResponse<LightingSummary>>({
    url: `/yeyan1996/IOT/1.0.0/lightingSummary`,
    method: "get",
    params: {},
    data: {}
  });
