/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
 * @date 2016-12-22 07:36
 **/

import axios from "axios";

/** 
 * @description Price Estimates 
 * @param {{
    "start_latitude": number
    "start_longitude": number
    "end_latitude": number
    "end_longitude": number
}} params    
**/
export const priceByGet = (params) =>
  axios.request({
    url: `/v1/estimates/price`,
    method: "get",
    params: params,
    data: {}
  });

/** 
 * @description Time Estimates 
 * @param {{
    "start_latitude": number
    "start_longitude": number
    "customer_uuid": string
    "product_id": string
}} params    
**/
export const timeByGet = (params) =>
  axios.request({
    url: `/v1/estimates/time`,
    method: "get",
    params: params,
    data: {}
  });
