/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
 * @date 2016-12-22 07:36
 **/

import axios from "axios";

/**
 * @description Price Estimates
 * @param {Object} params
 * @param {number} params.start_latitude - Latitude component of start location.
 * @param {number} params.start_longitude - Longitude component of start location.
 * @param {number} params.end_latitude - Latitude component of end location.
 * @param {number} params.end_longitude - Longitude component of end location.
 **/
export const priceByGet = (params) =>
  axios.request({
    url: `/v1/estimates/price`,
    method: "get",
    params: params,
    data: {}
  });

/**
 * @description Time Estimates
 * @param {Object} params
 * @param {number} params.start_latitude - Latitude component of start location.
 * @param {number} params.start_longitude - Longitude component of start location.
 * @param {string} params.customer_uuid - Unique customer identifier to be used for experience customization.
 * @param {string} params.product_id - Unique identifier representing a specific product for a given latitude & longitude.
 **/
export const timeByGet = (params) =>
  axios.request({
    url: `/v1/estimates/time`,
    method: "get",
    params: params,
    data: {}
  });
