/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
 * @date 2016-12-22 07:36
 **/

import axios from "axios";

/**
 * @description
 * @param {Object} _NOOP - never
 * @param {Object} pathParams
 * @param {string} pathParams.id
 **/
export const UpdateMapper = (_NOOP, { id }) =>
  axios.request({
    url: `/v1/crawler/v1/mapper/${id}`,
    method: "put",
    params: {},
    data: {}
  });
