/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
 * @date 2016-12-22 07:36
 **/

import axios from "axios";

/**
 * @description Product Types
 * @param {Object} params
 * @param {number} params.latitude - Latitude component of location.
 * @param {number} params.longitude - Longitude component of location.
 **/
export const productsTestByGet = (params) =>
  axios.request({
    url: `/v1/products-test`,
    method: "get",
    params: params,
    data: {}
  });
