/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
}
**/

import axios from "axios";

/** 分页上传设备地理坐标信息, 参数list的值为 List<DeviceLngLat>, 返回Result对象 */
export const uploadLngLatUsingPOST = (params: SwaggerList<void>) =>
  axios.request<any>({
    url: `/v1/dev/uploadLngLat`,
    method: "post",
    params: {},
    data: params
  });
