/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
 * @date 2016-12-22 07:36
 **/

import { PriceEstimate, Product } from "./interface/index.ts";
import axios from "axios";

/** Price Estimates */
export const priceByGet = (params: {
  start_latitude: number;
  start_longitude: number;
  end_latitude: number;
  end_longitude: number;
}) =>
  axios.request<PriceEstimate[]>({
    url: `/v1/estimates/price`,
    method: "get",
    params: params,
    data: {}
  });

/** Time Estimates */
export const timeByGet = (params: {
  start_latitude: number;
  start_longitude: number;
  customer_uuid?: string;
  product_id?: string;
}) =>
  axios.request<Product[]>({
    url: `/v1/estimates/time`,
    method: "get",
    params: params,
    data: {}
  });
