/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
}
**/

import axios from "axios";

export const UpdateMapper = (
  _NOOP: Record<string, never>,
  {
    id
  }: {
    id: string;
  }
) =>
  axios.request<string>({
    url: `/v1/crawler/v1/mapper/${id}`,
    method: "put",
    params: {},
    data: {}
  });
