/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Uber API
 * @description Move your app forward with the Uber API
 * @version 1.0.0
}
**/

import { Product } from "./interface/index.ts";
import axios from "axios";

/** Product Types */
export const productsByGet = (params: { latitude: number; longitude: number }) =>
  axios.request<Product[]>({
    url: `/v1/products`,
    method: "get",
    params: params,
    data: {}
  });
