/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title Swagger Petstore
 * @description This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 * @version 1.0.3
 * @date 2016-12-22 07:36
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'name': string
 *   }
 * } Category
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'category': Category
 *     'name': string
 *     'photoUrls': string[]
 *     'tags': Tag[]
 *     'status': "available" | "pending" | "sold"
 *   }
 * } Pet
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'name': string
 *   }
 * } Tag
**/

/**
 * @typedef {
 *   {
 *     'code': number
 *     'type': string
 *     'message': string
 *   }
 * } ApiResponse
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'petId': number
 *     'quantity': number
 *     'shipDate': string
 *     'status': "placed" | "approved" | "delivered"
 *     'complete': boolean
 *   }
 * } Order
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'username': string
 *     'firstName': string
 *     'lastName': string
 *     'email': string
 *     'password': string
 *     'phone': string
 *     'userStatus': number
 *   }
 * } User
**/