/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title home-iot-api
 * @description The API for the EatBacon IOT project
 * @version 1.0.0
}
**/

import { DeviceRegistrationInfo } from "./interface/index.ts";
import { AxiosResponse } from "axios";
import http from "http";

export const getDevices = (params: { skip?: number; limit?: number }) =>
  axios.request<string[]>({
    url: `/yeyan1996/IOT/1.0.0/devices`,
    method: "get",
    params: params,
    data: {}
  });

export const register = (params: DeviceRegistrationInfo) =>
  axios.request<any>({
    url: `/yeyan1996/IOT/1.0.0/devices`,
    method: "post",
    params: {},
    data: params
  });
