/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title home-iot-api
 * @description The API for the EatBacon IOT project
 * @version 1.0.0-oas3
 * @date 2016-12-22 07:36
**/

/**
 * @typedef {
 *   {
 *     'zones': LightingZone[]
 *     'zoneStatus': LightingZoneStatus[]
 *   }
 * } LightingSummary
**/

/**
 * @typedef {
 *   {
 *     'id': string
 *     'name': string
 *     'deviceId': number
 *     'deviceType': "dimmer" | "switch"
 *     'zone': string
 *   }
 * } LightingZone
**/

/**
 * @typedef {
 *   {
 *     'id': string
 *     'name': string
 *     'lastUpdate': string
 *     'level': number
 *   }
 * } LightingZoneStatus
**/

/**
 * @typedef {
 *   {
 *     'zones': TemperatureZone[]
 *     'zoneStatus': TemperatueZoneStatus[]
 *   }
 * } TemperatureSummary
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'name': string
 *     'inputPosition': number
 *     'outputPosition': number
 *     'zone': string
 *   }
 * } TemperatureZone
**/

/**
 * @typedef {
 *   {
 *     'id': string
 *     'name': string
 *     'value': number
 *     'units': "celsius" | "fahrenheit"
 *     'timestamp': string
 *   }
 * } TemperatueZoneStatus
**/

/**
 * @typedef {
 *   {
 *     'code': number
 *     'message': string
 *   }
 * } ApiResponse
**/

/**
 * @typedef {
 *   {
 *     'id': string
 *     'state': string
 *   }
 * } HeaterState
**/

/**
 * @typedef {
 *   {
 *     'id': string
 *     'name': string
 *     'lastUpdate': string
 *     'level': number
 *   }
 * } DeviceState
**/

/**
 * @typedef {
 *   {
 *     'city': City
 *     'values': Forecast[]
 *   }
 * } ForecastResponse
**/

/**
 * @typedef {
 *   {
 *     'date': string
 *     'pressure': number
 *     'humidity': number
 *     'windSpeed': number
 *     'clouds': number
 *     'temperature': ForecastTemperature
 *     'weather': WeatherForecast
 *   }
 * } Forecast
**/

/**
 * @typedef {
 *   {
 *     'id': number
 *     'name': string
 *     'lat': number
 *     'lon': number
 *     'country': string
 *   }
 * } City
**/

/**
 * @typedef {
 *   {
 *     'low': number
 *     'high': number
 *     'morning': number
 *     'day': number
 *     'evening': number
 *     'night': number
 *   }
 * } ForecastTemperature
**/

/**
 * @typedef {
 *   {
 *     'summary': string
 *     'description': string
 *     'icon': string
 *   }
 * } WeatherForecast
**/

/**
 * @typedef {
 *   {
 *     'uri': string
 *     'id': string
 *   }
 * } DeviceRegistrationInfo
**/