import { genPath } from './gen/path'
import { Method, parsePath } from './parse/path'
import { OpenAPIV2 } from 'openapi-types'
import { ConfigClient } from './utils'
import { genInterface } from './gen/interface'
import {
  parseInterface,
  shouldSkipGenerate,
  recursiveMap,
  buildInInterfaces,
} from './parse/interface'
import { pipe, curry } from 'lodash/fp'
import { formatCode } from './utils'
import { mergeDefaultConfig } from './default'

const freeSwaggerClient = (
  config: ConfigClient,
  url?: string,
  method?: Method
): string => {
  const chooseAll = !url || !method
  if (chooseAll) return ''

  const mergedConfig = mergeDefaultConfig(config)

  // api 名字
  const name: OpenAPIV2.OperationObject['operationId'] =
    config.source.paths[url!][method!].operationId
  if (!name) return ''

  const api = parsePath(
    name,
    `${config.source.basePath}${url}`,
    method!,
    config.source.paths[url!][method!]
  )

  const code = genPath(api, mergedConfig.templateFunction)
  return formatCode(mergedConfig.lang)(code)
}

// 生成单个 interface 代码
const compileInterface = (
  source: OpenAPIV2.Document,
  interfaceName: string
): string => {
  if (!source.definitions) return ''
  return source.definitions[interfaceName] && !shouldSkipGenerate(interfaceName)
    ? pipe(
        curry(parseInterface)(curry.placeholder, interfaceName, false),
        genInterface,
        formatCode('ts')
      )(source.definitions)
    : ''
}

// 生成全量 interface 代码
const compileInterfaces = (
  source: OpenAPIV2.Document,
  interfaceName?: string
): string => {
  if (!source.definitions) return ''
  if (interfaceName) {
    return compileInterface(source, interfaceName)
  } else {
    const headerCode = `// @ts-nocheck\n/* eslint-disable */\n// generated by free-swagger-client\n\n`
    const buildInInterfaceCode = Object.keys(buildInInterfaces).reduce(
      (acc, cur) => acc + buildInInterfaces[cur].code,
      ''
    )
    const interfaceCode = Object.keys(source.definitions).reduce(
      (acc, cur) => acc + compileInterface(source, cur),
      ''
    )
    const interfaceWithGenericCode = Object.keys(recursiveMap).reduce(
      (acc, cur) => acc + formatCode('ts')(genInterface(recursiveMap[cur])),
      ''
    )
    return formatCode('ts')(
      headerCode +
        buildInInterfaceCode +
        interfaceCode +
        interfaceWithGenericCode
    )
  }
}

export default freeSwaggerClient
export { compileInterfaces }
export * from './default/template'
export * from './utils'
export * from './gen/path'
export * from './parse/path'
