// generated by free-swagger
/* eslint-disable */
import axios from "axios";

export const GetAuditLogs = (params) =>
  axios.request({
    url: `/api/services/app/AuditLog/GetAuditLogs`,
    method: "get",
    params: params,
    data: {}
  });
