/* eslint-disable */
// generated by free-swagger

import axios from "axios";

export const UpdateMapper = (params, { id }) =>
  axios.request({
    url: `/crawler/v1/mapper/${id}`,
    method: "put",
    params: {},
    data: {}
  });
