/* eslint-disable */
// generated by free-swagger

import axios from "axios";

// Get user by user name
export const getUserByName = (params, { username }) =>
  axios.request({
    url: `/v2/user/${username}`,
    method: "get",
    params: {},
    data: {}
  });

// Updated user
export const updateUser = (params, { username }) =>
  axios.request({
    url: `/v2/user/${username}`,
    method: "put",
    params: {},
    data: params
  });

// Delete user
export const deleteUser = (params, { username }) =>
  axios.request({
    url: `/v2/user/${username}`,
    method: "delete",
    params: {},
    data: {}
  });

// Logs user into the system
export const loginUser = (params) =>
  axios.request({
    url: `/v2/user/login`,
    method: "get",
    params: params,
    data: {}
  });

// Logs out current logged in user session
export const logoutUser = () =>
  axios.request({
    url: `/v2/user/logout`,
    method: "get",
    params: {},
    data: {}
  });

// Create user
export const createUser = (params) =>
  axios.request({
    url: `/v2/user`,
    method: "post",
    params: {},
    data: params
  });

// Creates list of users with given input array
export const createUsersWithArrayInput = (params) =>
  axios.request({
    url: `/v2/user/createWithArray`,
    method: "post",
    params: {},
    data: params
  });

// Creates list of users with given input array
export const createUsersWithListInput = (params) =>
  axios.request({
    url: `/v2/user/createWithList`,
    method: "post",
    params: {},
    data: params
  });
