/* eslint-disable */
// @ts-nocheck
// generated by free-swagger

import {
  TemperatureSummary,
  ForecastResponse,
  TemperatueZoneStatus,
  HeaterState,
  ApiResponse
} from "./interface";
import { AxiosResponse } from "axios";
import http from "http";

export const temperatureSummary = () =>
  http.request<TemperatureSummary, AxiosResponse<TemperatureSummary>>({
    url: `/yeyan1996/IOT/1.0.0/temperature`,
    method: "get",
    params: {},
    data: {}
  });

export const getForecast = (
  params: { [key: string]: never },
  {
    days
  }: {
    days: number;
  }
) =>
  http.request<ForecastResponse, AxiosResponse<ForecastResponse>>({
    url: `/yeyan1996/IOT/1.0.0/temperature/forecast/${days}`,
    method: "get",
    params: {},
    data: {}
  });

export const getZoneTemperature = (
  params: { [key: string]: never },
  {
    zoneId
  }: {
    zoneId: string;
  }
) =>
  http.request<TemperatueZoneStatus, AxiosResponse<TemperatueZoneStatus>>({
    url: `/yeyan1996/IOT/1.0.0/temperature/${zoneId}`,
    method: "get",
    params: {},
    data: {}
  });

export const getHeaterState = (
  params: { [key: string]: never },
  {
    zoneId
  }: {
    zoneId: string;
  }
) =>
  http.request<HeaterState, AxiosResponse<HeaterState>>({
    url: `/yeyan1996/IOT/1.0.0/temperature/${zoneId}/heater`,
    method: "get",
    params: {},
    data: {}
  });

export const setHeaterState = (
  params: { [key: string]: never },
  {
    zoneId,
    state
  }: {
    zoneId: string;
    state: string;
  }
) =>
  http.request<ApiResponse, AxiosResponse<ApiResponse>>({
    url: `/yeyan1996/IOT/1.0.0/temperature/${zoneId}/heater/${state}`,
    method: "post",
    params: {},
    data: {}
  });
