/* eslint-disable */
// generated by free-swagger

import axios from "axios";
/**
 * @description 分页上传设备地理坐标信息, 参数list的值为 List<DeviceLngLat>, 返回Result对象
 * @param {JavaList<void>} params -设备地理坐标信息集合
 **/

// 分页上传设备地理坐标信息, 参数list的值为 List<DeviceLngLat>, 返回Result对象
export const uploadLngLatUsingPOST = (params) =>
  axios.request({
    url: `/v1/dev/uploadLngLat`,
    method: "post",
    params: {},
    data: params
  });
