/* eslint-disable */
// generated by free-swagger

import axios from "axios";
/**
 * @description
 * @param {Object} params -never
 * @param {Object} pathParams
 * @param {string} pathParams.id
 **/

export const UpdateMapper = (_NOOP, { id }) =>
  axios.request({
    url: `/v1/crawler/v1/mapper/${id}`,
    method: "put",
    params: {},
    data: {}
  });
