import { ClientConfig } from '../utils'
import { jsTemplate } from './template'

export const mergeDefaultParams = (
  config: ClientConfig
): Required<ClientConfig> => ({
  useJsDoc: false,
  lang: 'js',
  templateFunction: eval(jsTemplate),
  ...config,
})

export const DEFAULT_HEAD_JS_DOC_TYPES = `// generated by free-swagger-client
// @see https://www.npmjs.com/package/free-swagger-client
    `
