/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title home-iot-api
 * @description The API for the EatBacon IOT project
 * @version 1.0.0-oas3
}
**/

import axios from "axios";

/**
 * @description
 **/
export const temperatureSummary = () =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/temperature`,
    method: "get",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP - never
 * @param {Object} pathParams
 * @param {number} pathParams.days
 **/
export const getForecast = (_NOOP, { days }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/temperature/forecast/${days}`,
    method: "get",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP - never
 * @param {Object} pathParams
 * @param {string} pathParams.zoneId
 **/
export const getZoneTemperature = (_NOOP, { zoneId }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/temperature/${zoneId}`,
    method: "get",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP - never
 * @param {Object} pathParams
 * @param {string} pathParams.zoneId
 **/
export const getHeaterState = (_NOOP, { zoneId }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/temperature/${zoneId}/heater`,
    method: "get",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP - never
 * @param {Object} pathParams
 * @param {string} pathParams.zoneId
 * @param {string} pathParams.state
 **/
export const setHeaterState = (_NOOP, { zoneId, state }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/temperature/${zoneId}/heater/${state}`,
    method: "post",
    params: {},
    data: {}
  });
