/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger
 * @see https://www.npmjs.com/package/free-swagger
 * @title home-iot-api
 * @description The API for the EatBacon IOT project
 * @version 1.0.0-oas3
 * @date 2016-12-22 07:36
 **/

import axios from "axios";

/**
 * @description
 * @param {Object} _NOOP -never
 * @param {Object} pathParams
 * @param {string} pathParams.deviceId
 * @param {number} pathParams.value
 **/
export const setDimmer = (_NOOP, { deviceId, value }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/lighting/dimmers/${deviceId}/${value}`,
    method: "post",
    params: {},
    data: {}
  });

/** 
 * @description  
 * @param {{
    "units": string
}} params  
 * @param {Object} pathParams
 * @param {string} pathParams.deviceId 
 * @param {number} pathParams.value 
 * @param {number} pathParams.timeunit   
**/
export const setDimmerTimer = (params, { deviceId, value, timeunit }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/lighting/dimmers/${deviceId}/${value}/timer/${timeunit}`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP -never
 * @param {Object} pathParams
 * @param {string} pathParams.deviceId
 **/
export const getSwitchState = (_NOOP, { deviceId }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/lighting/switches/${deviceId}`,
    method: "get",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP -never
 * @param {Object} pathParams
 * @param {string} pathParams.deviceId
 * @param {string} pathParams.value
 **/
export const setSwitch = (_NOOP, { deviceId, value }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/lighting/switches/${deviceId}/${value}`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} _NOOP -never
 * @param {Object} pathParams
 * @param {string} pathParams.deviceId
 * @param {string} pathParams.value
 * @param {number} pathParams.minutes
 **/
export const setSwitchTimer = (_NOOP, { deviceId, value, minutes }) =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/lighting/switches/${deviceId}/${value}/timer/${minutes}`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description
 **/
export const getLightingSummary = () =>
  axios.request({
    url: `/yeyan1996/IOT/1.0.0/lightingSummary`,
    method: "get",
    params: {},
    data: {}
  });
