// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import { ApprovalOperateRecordResponse, ApprovalPreviewResponse, ApprovalRecordResponse } from "./interface";
import axios, { AxiosResponse } from "axios";

// 审批通过或驳回接口
export const approveOrRejectUsingPOST = (params: 审批通过或驳回接口请求) =>
  axios.request<any, AxiosResponse<any>>({
    url: `/v1/approval/approveOrReject`,
    method: "post",
    params: {},
    data: params
  });

// approveProcessCallBack
export const approveProcessCallBackUsingPOST = (params: object) =>
  axios.request<any, AxiosResponse<any>>({
    url: `/v1/approval/approveProcessCallBack`,
    method: "post",
    params: {},
    data: params
  });

// 修改记录列表
export const listApprovalOperateRecordByApprovalRecordIdUsingGET = (params: { taskId?: string }) =>
  axios.request<ApprovalOperateRecordResponse[], AxiosResponse<ApprovalOperateRecordResponse[]>>({
    url: `/v1/approval/modifyRecords`,
    method: "get",
    params: params,
    data: {}
  });

// 流程预览接口
export const listApprovalPreviewByBusinessDataIdUsingGET = (params: { businessDataId?: string }) =>
  axios.request<ApprovalPreviewResponse, AxiosResponse<ApprovalPreviewResponse>>({
    url: `/v1/approval/preview`,
    method: "get",
    params: params,
    data: {}
  });

// 审批记录列表
export const listApprovalRecordByBusinessDataIdUsingGET = (params: { businessDataId?: string }) =>
  axios.request<ApprovalRecordResponse[], AxiosResponse<ApprovalRecordResponse[]>>({
    url: `/v1/approval/records`,
    method: "get",
    params: params,
    data: {}
  });

// submitProcessCallBack
export const submitProcessCallBackUsingPOST = (params: object) =>
  axios.request<any, AxiosResponse<any>>({
    url: `/v1/approval/submitProcessCallBack`,
    method: "post",
    params: {},
    data: params
  });
