// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import { Result, PageInfo, DocumentQueryResponse, DocumentRequest, DocumentDetailResponse } from "./interface";
import axios, { AxiosResponse } from "axios";

// 查询单据定义列表
export const queryDocumentListUsingGET = (params: {
  keyword?: string;
  pageNum?: number;
  pageSize?: number;
  status?: boolean;
}) =>
  axios.request<Result<PageInfo<DocumentQueryResponse>>, AxiosResponse<Result<PageInfo<DocumentQueryResponse>>>>({
    url: `/v1/documents`,
    method: "get",
    params: params,
    data: {}
  });

// 新增单据定义
export const createDocumentUsingPOST = (params: DocumentRequest) =>
  axios.request<Result, AxiosResponse<Result>>({
    url: `/v1/documents`,
    method: "post",
    params: {},
    data: params
  });

// 复制单据定义
export const copyDocumentUsingPOST = (
  params: DocumentRequest,
  { originUnionId } = {
    originUnionId: string
  }
) =>
  axios.request<Result, AxiosResponse<Result>>({
    url: `/v1/documents/${originUnionId}`,
    method: "post",
    params: {},
    data: params
  });

// 查询单据定义详情
export const queryDocumentDetailUsingGET = (
  params: { [key: string]: never },
  { unionId } = {
    unionId: string
  }
) =>
  axios.request<Result<DocumentDetailResponse>, AxiosResponse<Result<DocumentDetailResponse>>>({
    url: `/v1/documents/${unionId}`,
    method: "get",
    params: {},
    data: {}
  });

// 编辑单据定义
export const editDocumentUsingPUT = (
  params: DocumentRequest,
  { unionId } = {
    unionId: string
  }
) =>
  axios.request<Result, AxiosResponse<Result>>({
    url: `/v1/documents/${unionId}`,
    method: "put",
    params: {},
    data: params
  });
