// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import { ReimbursementEntrySaveRequest, Result } from "./interface";
import axios, { AxiosResponse } from "axios";

// 创建单据明细
export const createReimbursementUsingPOST = (params: ReimbursementEntrySaveRequest) =>
  axios.request<Result<Void>, AxiosResponse<Result<Void>>>({
    url: `/v1/reimbursement/expense-entries`,
    method: "post",
    params: {},
    data: params
  });

// 更新单据明细
export const saveReimbursementUsingPUT = (
  params: ReimbursementEntrySaveRequest,
  { unionId } = {
    unionId: string
  }
) =>
  axios.request<Result<Void>, AxiosResponse<Result<Void>>>({
    url: `/v1/reimbursement/expense-entries/${unionId}`,
    method: "put",
    params: {},
    data: params
  });
