// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import axios, { AxiosResponse } from "axios";

// checkHealth
export const checkHealthUsingGET = () =>
  axios.request<string, AxiosResponse<string>>({
    url: `/health`,
    method: "get",
    params: {},
    data: {}
  });
