// @ts-nocheck
/* eslint-disable */
// generated by free-swagger-client

export interface JavaMap<T, U> {
  [key: T]: U;
}

export interface JavaList<T> {
  [index: number]: T;
}
export interface PageInfo<T> {
  list?: T[];
  endRow?: number;
  firstPage?: number;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  isFirstPage?: boolean;
  isLastPage?: boolean;
  lastPage?: number;
  navigateFirstPage?: number;
  navigateLastPage?: number;
  navigatePages?: number;
  navigatepageNums?: number[];
  nextPage?: number;
  pageNum?: number;
  pageSize?: number;
  pages?: number;
  prePage?: number;
  size?: number;
  startRow?: number;
  total?: number;
}
export interface PageableResponse<T> {
  list?: T[];
  pageNum?: number;
  pageSize?: number;
  total?: number;
}
export interface Result<T> {
  data?: T;
  code?: number;
  msg?: string;
}
export interface AccessCompany {
  companyName?: string; // 公司名称
  unionId?: string; // 公司唯一关联ID
}
export interface AccessEmpCluster {
  clusterName?: string; // 人员组名称
  unionId?: string; // 人员组唯一关联ID
}
export interface AccessMetadata {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 启用组织
  accessEmpTypeEnum?: "ALL" | "PART"; // 人员组类型
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 所属层级
  companies?: AccessCompany[]; // 指定公司列表
  empClusters?: AccessEmpCluster[]; // 指定人员组明细
  groupUnionId?: string; // 集团ID
  sourceType?:
    | "TRAVEL_APPLY"
    | "EXPENSE_APPLY"
    | "TRAVEL_REIMBURSEMENT"
    | "EXPENSE_REIMBURSEMENT"
    | "ADVANCE"
    | "REPAYMENT"
    | "EXPENSE_ENTRY"
    | "PAYMENT_ENTRY"
    | "ADVANCE_ENTRY"
    | "REPAYMENT_ENTRY"
    | "ITINERARY_ENTRY"
    | "ENUM"
    | "EMPLOYEE_CLUSTER"; // 资源类型
  tenantUnionId?: string; // 租户ID
}
export interface AdvanceTypeVo {
  advanceTypeName?: string; // 借款类型名称
  unionId?: string; // 借款类型编码
}
export interface ApprovalOperateRecordResponse {
  contentAfter?: string;
  contentBefore?: string;
  contentName?: string;
  operateTime?: string;
  taskId?: string;
}
export interface ApprovalPreviewNode {
  approvalUserInfos?: ApprovalUserInfo[];
  candidateList?: ApprovalUserInfo[];
  nodeId?: string;
  nodeName?: string;
  taskInstanceId?: string;
}
export interface ApprovalPreviewResponse {
  doneNodeList?: ApprovalPreviewNode[];
  forecastNodeList?: ApprovalPreviewNode[];
  todoNodeList?: ApprovalPreviewNode[];
}
export interface ApprovalRecordResponse {
  approvalComment?: string;
  approvalTime?: string;
  approvalUserAvator?: string;
  approvalUserId?: string;
  approvalUserName?: string;
  result?: string;
  taskId?: string;
  taskName?: string;
}
export interface ApprovalUserInfo {
  headImage?: string;
  name?: string;
  userId?: string;
}
export interface DocumentDetailResponse {
  accessCompanyType?: "ALL" | "PART"; // 启用公司 范围
  accessEmpTypeEnum?: "ALL" | "PART"; // 适用人员组
  accessHierarchy?: "GROUP" | "COMPANY"; // 所属层级
  advanceTypes?: AdvanceTypeVo[]; // 适用借款类型
  category?:
    | "TRAVEL_REIMBURSEMENT"
    | "EXPENSE_REIMBURSEMENT"
    | "TRAVEL_APPLY"
    | "EXPENSE_APPLY"
    | "ADVANCE"
    | "REPAYMENT"; // 单据大类
  code?: string; // 单据编码
  comment?: string; // 备注
  companies?: AccessCompany[]; // 启用公司
  employeeClusters?: AccessEmpCluster[]; // 适用人员组
  expenseTypes?: ExpenseTypeVo[]; // 适用费用类型
  groupUnionId?: string; // 集团编码
  itineraryTypes?: ItineraryTypeVo[]; // 适用行程类型
  name?: string; // 单据名称
  payTypes?: PayTypeVo[]; // 适用付款类型
  status?: boolean; // 状态，true:启用，false:禁用
  tenantUnionId?: string; // 租户编码
  unionId?: string; // 关联ID
}
export interface DocumentQueryResponse {
  accessCompanyType?: "ALL" | "PART"; // 启用公司范围
  accessHierarchy?: "GROUP" | "COMPANY"; // 所属层级
  category?:
    | "TRAVEL_REIMBURSEMENT"
    | "EXPENSE_REIMBURSEMENT"
    | "TRAVEL_APPLY"
    | "EXPENSE_APPLY"
    | "ADVANCE"
    | "REPAYMENT"; // 单据大类
  code?: string; // 单据编码
  comment?: string; // 备注
  companies?: AccessCompany[]; // 启用公司范围
  groupUnionId?: string; // 集团编码
  name?: string; // 单据名称
  status?: boolean; // 状态，true:启用，false:禁用
  tenantUnionId?: string; // 租户编码
  unionId?: string; // 关联ID
}
export interface DocumentRequest {
  accessCompanyType: "ALL" | "PART"; // 启用公司范围
  accessEmpType: "ALL" | "PART"; // 适用人员组类型
  accessHierarchy: "GROUP" | "COMPANY"; // 所属层级
  advanceTypeScopeType?: "ALL" | "PART"; // 适用借款类型 范围
  advanceTypes?: string[]; // 适用借款类型
  allowDirectAdvanceConfig?: boolean; // 允许直接借款，false:不允许，true:允许
  allowMultiReimburseConfig?: boolean; // 允许多次报销，false:不允许，true:允许
  applyBeforeConfig?: string; // 事先申请
  applyExceedControlConfig?: string; // 超申请控制
  budgetReserveConfig?: boolean; // 预算占用，false:不保留，true:保留
  category:
    | "TRAVEL_REIMBURSEMENT"
    | "EXPENSE_REIMBURSEMENT"
    | "TRAVEL_APPLY"
    | "EXPENSE_APPLY"
    | "ADVANCE"
    | "REPAYMENT"; // 单据大类
  code: string; // 单据编码
  comment?: string; // 备注
  currentEmpNo?: string; // 当前操作人工号(员工侧)
  currentEmpUnionId?: string; // 当前操作人unionId(员工侧)
  empClusterUnionIds?: string[]; // 员工组ID列表(员工侧)
  empCompanyUnionIds?: string[]; // 公司ID(员工侧)
  expenseTypeScopeType?: "ALL" | "PART"; // 适用费用类型 范围
  expenseTypes?: string[]; // 适用费用类型
  formUnionId: string; // 关联表单ID
  groupUnionId: string; // 集团编码
  itineraryTypeScopeType?: "ALL" | "PART"; // 适用行程类型 范围
  itineraryTypes?: string[]; // 适用行程类型
  multiAdvanceRowConfig?: boolean; // 多借款行，false:单行，true:多行
  multiPayRowConfig?: boolean; // 多付款行，false:单行，true:多行
  multiRepaymentRowConfig?: boolean; // 多还款行，false:单行，true:多行
  mustRelateAdvanceConfig?: boolean; // 必须关联借款，false:否，true:是
  name: string; // 单据名称
  originUnionId: string; // 用于复制，记录原unionId
  payTypeScopeType?: "ALL" | "PART"; // 适用付款类型 范围
  payTypes?: string[]; // 适用付款类型
  status: boolean; // 状态，true:启用，false:禁用
  tenantUnionId: string; // 租户编码
  unionId: string; // 关联ID
}
export interface DynamicDataModel {
  isActive?: boolean;
  isSystem?: boolean;
  key1?: string;
  key10?: string;
  key11?: string;
  key12?: string;
  key13?: string;
  key14?: string;
  key15?: string;
  key16?: string;
  key17?: string;
  key18?: string;
  key19?: string;
  key2?: string;
  key20?: string;
  key21?: string;
  key22?: string;
  key23?: string;
  key24?: string;
  key25?: string;
  key26?: string;
  key27?: string;
  key28?: string;
  key29?: string;
  key3?: string;
  key30?: string;
  key31?: string;
  key32?: string;
  key33?: string;
  key34?: string;
  key35?: string;
  key36?: string;
  key37?: string;
  key38?: string;
  key39?: string;
  key4?: string;
  key40?: string;
  key5?: string;
  key6?: string;
  key7?: string;
  key8?: string;
  key9?: string;
}
export interface DynamicEnumDetail {
  accessMetadata?: AccessMetadata;
  createTime?: string;
  enumCode?: string;
  enumName?: string;
  isActive?: boolean;
  isBusiness?: boolean;
  isSystem?: boolean;
  level?: number;
  options?: DynamicEnumOptionMetadata[];
  unionId?: string;
  updateTime?: string;
}
export interface DynamicEnumMetadata {
  accessMetadata?: AccessMetadata;
  createTime?: string;
  enumCode?: string;
  enumName?: string;
  isActive?: boolean;
  isBusiness?: boolean;
  isSystem?: boolean;
  level?: number;
  unionId?: string;
  updateTime?: string;
}
export interface DynamicEnumModel {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 启用公司 ALL:集团通用 PART: 指定公司
  accessCompanyUnionIds?: string[]; // 授权公司唯一ID数组
  accessEmpClusterUnionIds?: string[]; // 授权员工组唯一ID数组
  accessEmpTypeEnum?: "ALL" | "PART"; // 人员组类型 ALL: 全部 PART: 部分
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 所属层级 GROUP: 集团 COMPANY: 公司
  enumCode?: string; // 枚举编码
  enumName?: string; // 枚举名称
  isActive?: boolean; // 是否启用
  isBusiness?: boolean; // 是否值列表(C端)
  isSystem?: boolean; // 是否系统级枚举
}
export interface DynamicEnumOptionMetadata {
  createTime?: string;
  description?: string;
  enumUnionId?: string;
  isActive?: boolean;
  isDefault?: boolean;
  isSystem?: boolean;
  parentValue?: string;
  sortOrder?: number;
  text?: string;
  unionId?: string;
  updateTime?: string;
  value?: string;
}
export interface DynamicEnumOptionModel {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 启用公司 ALL:集团通用 PART: 指定公司
  accessCompanyUnionIds?: string[]; // 授权公司唯一ID数组
  accessEmpClusterUnionIds?: string[]; // 授权员工组唯一ID数组
  accessEmpTypeEnum?: "ALL" | "PART"; // 人员组类型 ALL: 全部 PART: 部分
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 所属层级 GROUP: 集团 COMPANY: 公司
  description?: string; // 枚举说明
  isActive?: boolean; // 是否启用
  isDefault?: boolean; // 是否默认选项
  isSystem?: boolean; // 是否系统级
  parentValue?: string; // 上级枚举值
  sortOrder?: number; // 排序
  text?: string; // 枚举展示文本
  value?: string; // 枚举值
}
export interface DynamicFieldMetadata {
  createTime?: string;
  dataColumn?: string;
  description?: string;
  enumInfo?: Enum;
  extraDataSchema?: string;
  extraUrl?: string;
  fieldCode?: string;
  fieldName?: string;
  fieldType?: string;
  formUnionId?: string;
  isActive?: boolean;
  isAssigned?: boolean;
  isAutoAssignValue?: boolean;
  isDeletable?: boolean;
  isDeleted?: boolean;
  isDisplay?: boolean;
  isMultiLang?: boolean;
  isReadonly?: boolean;
  isRequired?: boolean;
  isSearch?: boolean;
  isShare?: boolean;
  isUnique?: boolean;
  label?: string;
  maxLength?: number;
  meta?: string;
  minLength?: number;
  moduleUnionId?: string;
  placeHolder?: string;
  property?: string;
  propertyUnionId?: string;
  scale?: number;
  scope?: string[];
  sortOrder?: number;
  span?: number;
  unionId?: string;
  updateTime?: string;
}
export interface DynamicFieldModel {
  dataColumn?: string; // 数据列
  description?: string; // 字段说明
  extraDataSchema?: string; // 第三方数据源解析结构
  extraUrl?: string; // 第三方数据源url
  fieldCode?: string; // 字段编码
  fieldName?: string; // 字段名称
  fieldType?: string; // 字段类型
  formUnionId?: string; // 表单唯一ID
  isActive?: boolean; // 是否启用
  isAssigned?: boolean; // 是否系统预置字段
  isAutoAssignValue?: boolean; // 是否自动赋默认值
  isDeletable?: boolean; // 是否可删除
  isDeleted?: boolean; // 是否逻辑删除
  isDisplay?: boolean; // 是否作为列展示
  isMultiLang?: boolean; // 是否多语言文本字段
  isReadonly?: boolean; // 是否只读
  isRequired?: boolean; // 是否必填
  isSearch?: boolean; // 字段是否在搜索页作为搜索条件
  isShare?: boolean; // 是否作为分摊字段
  isUnique?: boolean; // 字段值是否唯一
  label?: string; // 标题
  maxLength?: number; // 字段最大长度
  meta?: string; // 字段规则
  minLength?: number; // 字段最小长度
  moduleUnionId?: string; // 模块唯一ID
  placeHolder?: string; // 未填内容时的提示
  property?: string; // 业务属性
  propertyUnionId?: string; // 值列表/自定义纬度唯一ID
  scale?: number; // 小数位数
  scope?: string[]; // 适用范围
  sortOrder?: number; // 排序值，小的靠前
  span?: number; // 字段占一行的span值
}
export interface DynamicFormModel {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 启用公司 ALL:集团通用 PART: 指定公司
  accessCompanyUnionIds?: string[]; // 授权公司唯一ID数组
  accessEmpClusterUnionIds?: string[]; // 授权员工组唯一ID数组
  accessEmpTypeEnum?: "ALL" | "PART"; // 人员组类型 ALL: 全部 PART: 部分
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 所属层级 GROUP: 集团 COMPANY: 公司
  description?: string; // 表单描述
  formCode?: string; // 表单编码
  formName?: string; // 表单名称
  formType?: string; // 表单类型
  isActive?: boolean; // 是否启用
  isSystem?: boolean; // 是否系统级
  level?: string; // 表单层级
  moduleUnionId?: string; // 模块唯一ID
  showLineNumber?: boolean; // 表格中是否展示行号
}
export interface DynamicModuleMetadata {
  createTime?: string;
  moduleCode?: string;
  moduleName?: string;
  unionId?: string;
  updateTime?: string;
}
export interface DynamicModuleModel {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 启用公司 ALL:集团通用 PART: 指定公司
  accessCompanyUnionIds?: string[]; // 授权公司唯一ID数组
  accessEmpClusterUnionIds?: string[]; // 授权员工组唯一ID数组
  accessEmpTypeEnum?: "ALL" | "PART"; // 人员组类型 ALL: 全部 PART: 部分
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 所属层级 GROUP: 集团 COMPANY: 公司
  isSystem?: boolean; // 是否系统级枚举
  moduleCode?: string; // 模块编码
  moduleName?: string; // 模块名称
}
export interface Enum {
  enumCode?: string;
  enumName?: string;
  enumOptions?: EnumOption[];
  enumUnionId?: string;
}
export interface EnumOption {
  enumOptionUnionId?: string;
  isDefault?: boolean;
  text?: string;
  value?: string;
}
export interface ExpenseCategoryDo {
  code?: string;
  createTime?: string;
  creator?: string;
  groupUnionId?: string;
  id?: number;
  isDeleted?: boolean;
  modifier?: string;
  name?: string;
  parentCode?: string;
  tenantUnionId?: string;
  unionId?: string;
  updateTime?: string;
}
export interface ExpenseCategoryRequest {
  code: string; // 费用大类编码
  currentEmpNo?: string; // 当前操作人工号(员工侧)
  currentEmpUnionId?: string; // 当前操作人unionId(员工侧)
  empClusterUnionIds?: string[]; // 员工组ID列表(员工侧)
  empCompanyUnionIds?: string[]; // 公司ID(员工侧)
  expenseCategory?: ExpenseCategoryDo;
  groupUnionId?: string; // 集团ID(员工侧)
  isDeleted?: boolean; // true为删除，false为不删除，不传默认为false
  name: string; // 费用大类名称
  parentCode?: string; // 父级费用大类编码
  tenantUnionId?: string; // 租户ID(员工侧)
  unionId?: string; // 费用大类unionId
  unionIdList?: string[]; // 批量删除费用大类unionIdList
}
export interface ExpenseCategoryResponse {
  code?: string;
  name?: string;
  unionId?: string;
}
export interface ExpenseTypeDetailResponse {
  accessCompanyTypeEnum?: "ALL" | "PART";
  accessEmpTypeEnum?: "ALL" | "PART";
  accessHierarchyEnum?: "GROUP" | "COMPANY";
  allowanceType?: "TRAVEL_ALLOWANCE" | "NOT_ALLOWANCE";
  companyNameList?: string[];
  description?: string;
  empClusterNameList?: string[];
  expenseCategoryCode?: string;
  expenseCategoryName?: string;
  expenseCategoryUnionId?: string;
  expenseTypeCode?: string;
  expenseTypeName?: string;
  formName?: string;
  formUnionId?: string;
  isActive?: boolean;
  isAllocation?: boolean;
  isAllowedInvoices?: boolean;
  isWithInvoiceEnum?: "FIELD_REQUIRED_WITH_INVOICE" | "FIELD_NOT_REQUIRED_WITH_INVOICE" | "NO_INVOICE";
  paymentMethod?: "PERSONAL" | "BUSINESS_CARD";
  unionId?: string;
}
export interface ExpenseTypeDo {
  allowanceType?: "TRAVEL_ALLOWANCE" | "NOT_ALLOWANCE";
  categoryUnionId?: string;
  code?: string;
  createTime?: string;
  creator?: string;
  description?: string;
  formUnionId?: string;
  groupUnionId?: string;
  id?: number;
  isActive?: boolean;
  isAllocation?: boolean;
  isAllowedInvoices?: boolean;
  isDeleted?: boolean;
  isGroup?: boolean;
  isWithInvoice?: "FIELD_REQUIRED_WITH_INVOICE" | "FIELD_NOT_REQUIRED_WITH_INVOICE" | "NO_INVOICE";
  modifier?: string;
  name?: string;
  paymentMethod?: "PERSONAL" | "BUSINESS_CARD";
  tenantUnionId?: string;
  unionId?: string;
  updateTime?: string;
}
export interface ExpenseTypeRequest {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 集团通用全部传ALL，指定公司传PART
  accessEmpTypeEnum?: "ALL" | "PART"; // 适用人员全部传ALL，指定人员组传PART
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 层级选择集团传GROUP,选择公司传COMPANY
  allowanceType?: "TRAVEL_ALLOWANCE" | "NOT_ALLOWANCE"; // TRAVEL_ALLOWANCE是差旅补贴，NOT_ALLOWANCE是非补贴
  categoryUnionId?: string; // 费用大类关联id
  code?: string; // 费用类型编码
  currentEmpNo?: string; // 当前操作人工号(员工侧)
  currentEmpUnionId?: string; // 当前操作人unionId(员工侧)
  description?: string; // 费用类型描述
  empClusterUnionIds?: string[]; // 员工组ID列表(员工侧)
  empCompanyUnionIds?: string[]; // 公司ID(员工侧)
  expenseType?: ExpenseTypeDo;
  formUnionId?: string; // 费用类型表单关联id
  groupUnionId?: string; // 集团ID(员工侧)
  isActive?: boolean; // 是否启用
  isAllocation?: boolean; // 是否分摊
  isAllowedInvoices?: boolean; // 是否允许关联多张发票
  isWithInvoice?: "FIELD_REQUIRED_WITH_INVOICE" | "FIELD_NOT_REQUIRED_WITH_INVOICE" | "NO_INVOICE"; // FIELD_REQUIRED_WITH_INVOICE是有发票控件且必填，FIELD_NOT_REQUIRED_WITH_INVOICE是有发票控件但不必填，NO_INVOICE是无发票控件
  name?: string; // 费用类型名称
  originUnionId?: string; // 被复制记录的unionId，复制操作时传
  pageNum?: number;
  pageSize?: number;
  paymentMethod?: "PERSONAL" | "BUSINESS_CARD"; // PERSONAL是个人支付，BUSINESS_CARD是商务卡支付
  tenantUnionId?: string; // 租户ID(员工侧)
  unionId?: string; // 当前记录的unionId，复制操作时不传
}
export interface ExpenseTypeResponse {
  accessCompanyTypeEnum?: "ALL" | "PART";
  accessHierarchyEnum?: "GROUP" | "COMPANY";
  companyNameList?: string[];
  expenseCategoryCode?: string;
  expenseCategoryName?: string;
  expenseTypeCode?: string;
  expenseTypeName?: string;
  isActive?: boolean;
  unionId?: string;
}
export interface ExpenseTypeVo {
  expenseTypeName?: string; // 费用类型名称
  unionId?: string; // 费用类型编码
}
export interface ItineraryTypeVo {
  itineraryTypeName?: string; // 行程类型名称
  unionId?: string; // 行程类型编码
}
export interface PayTypeVo {
  payTypeName?: string; // 付款类型名称
  unionId?: string; // 付款类型编码
}
export interface PaymentTypeDetailResponse {
  accessCompanyTypeEnum?: "ALL" | "PART";
  accessEmpTypeEnum?: "ALL" | "PART";
  accessHierarchyEnum?: "GROUP" | "COMPANY";
  comment?: string;
  companyNameList?: string[];
  empClusterNameList?: string[];
  formUnionId?: string;
  isActive?: boolean;
  paymentTypeCode?: string;
  paymentTypeName?: string;
  unionId?: string;
}
export interface PaymentTypeDo {
  code?: string;
  comment?: string;
  createTime?: string;
  creator?: string;
  formUnionId?: string;
  groupUnionId?: string;
  id?: number;
  isActive?: boolean;
  isDeleted?: boolean;
  isGroup?: boolean;
  modifier?: string;
  name?: string;
  tenantUnionId?: string;
  unionId?: string;
  updateTime?: string;
}
export interface PaymentTypeRequest {
  accessCompanyTypeEnum?: "ALL" | "PART"; // 集团通用全部传ALL，指定公司传PART
  accessEmpTypeEnum?: "ALL" | "PART"; // 适用人员全部传ALL，指定人员组传PART
  accessHierarchyEnum?: "GROUP" | "COMPANY"; // 层级选择集团传GROUP,选择公司传COMPANY
  code?: string; // 付款类型编码
  comment?: string; // 备注
  currentEmpNo?: string; // 当前操作人工号(员工侧)
  currentEmpUnionId?: string; // 当前操作人unionId(员工侧)
  empClusterUnionIds?: string[]; // 员工组ID列表(员工侧)
  empCompanyUnionIds?: string[]; // 公司ID(员工侧)
  formUnionId?: string; // 付款类型表单关联id
  groupUnionId?: string; // 集团ID(员工侧)
  isActive?: boolean; // 是否启用
  name?: string; // 付款类型名称
  pageNum?: number;
  pageSize?: number;
  paymentType?: PaymentTypeDo;
  tenantUnionId?: string; // 租户ID(员工侧)
  unionId?: string; // 付款类型关联id
}
export interface PaymentTypeResponse {
  accessCompanyTypeEnum?: "ALL" | "PART";
  accessHierarchyEnum?: "GROUP" | "COMPANY";
  comment?: string;
  companyNameList?: string[];
  isActive?: boolean;
  paymentTypeCode?: string;
  paymentTypeName?: string;
  unionId?: string;
}
export interface ReimbursementEntrySaveRequest {
  currentEmpNo?: string; // 当前操作人工号(员工侧)
  currentEmpUnionId?: string; // 当前操作人unionId(员工侧)
  dynamicFormData?: object;
  empClusterUnionIds?: string[]; // 员工组ID列表(员工侧)
  empCompanyUnionIds?: string[]; // 公司ID(员工侧)
  expenseTypeUnionId?: string;
  groupUnionId?: string; // 集团ID(员工侧)
  invoiceUnionIdList?: string[];
  reimbursementUnionId?: string;
  tenantUnionId?: string; // 租户ID(员工侧)
  unionId?: string;
}
export interface ReimbursementSaveRequest {
  currentEmpNo?: string; // 当前操作人工号(员工侧)
  currentEmpUnionId?: string; // 当前操作人unionId(员工侧)
  dynamicFormData?: object;
  empClusterUnionIds?: string[]; // 员工组ID列表(员工侧)
  empCompanyUnionIds?: string[]; // 公司ID(员工侧)
  groupUnionId?: string; // 集团ID(员工侧)
  tenantUnionId?: string; // 租户ID(员工侧)
  unionId?: string;
}
export interface 审批通过或驳回接口请求 {
  approvalUserId?: string; // 审批人id
  commandType?: string; // 操作类型
  taskComment?: string; // 审批意见
  taskId?: string; // 审批任务id
}
