// generated by free-swagger
// @ts-nocheck
/* eslint-disable */
import { Result, PageInfo, PaymentTypeResponse, PaymentTypeRequest, PaymentTypeDetailResponse } from "./interface";
import axios, { AxiosResponse } from "axios";

// 查询付款类型列表
export const queryPaymentTypeListUsingGET = (params: {
  accessCompanyTypeEnum?: string;
  accessEmpTypeEnum?: string;
  accessHierarchyEnum?: string;
  code?: string;
  comment?: string;
  currentEmpNo?: string;
  currentEmpUnionId?: string;
  empClusterUnionIds?: string;
  empCompanyUnionIds?: string;
  formUnionId?: string;
  groupUnionId?: string;
  isActive?: boolean;
  name?: string;
  pageNum?: number;
  pageSize?: number;
  "paymentType.code"?: string;
  "paymentType.comment"?: string;
  "paymentType.createTime"?: string;
  "paymentType.creator"?: string;
  "paymentType.formUnionId"?: string;
  "paymentType.groupUnionId"?: string;
  "paymentType.id"?: number;
  "paymentType.isActive"?: boolean;
  "paymentType.isDeleted"?: boolean;
  "paymentType.isGroup"?: boolean;
  "paymentType.modifier"?: string;
  "paymentType.name"?: string;
  "paymentType.tenantUnionId"?: string;
  "paymentType.unionId"?: string;
  "paymentType.updateTime"?: string;
  tenantUnionId?: string;
  unionId?: string;
}) =>
  axios.request<Result<PageInfo<PaymentTypeResponse>>, AxiosResponse<Result<PageInfo<PaymentTypeResponse>>>>({
    url: `/v1/admin/payment-types`,
    method: "get",
    params: params,
    data: {}
  });

// 新增付款类型
export const createPaymentTypeUsingPOST = (params: PaymentTypeRequest) =>
  axios.request<Result, AxiosResponse<Result>>({
    url: `/v1/admin/payment-types`,
    method: "post",
    params: {},
    data: params
  });

// 查询付款类型详情
export const queryPaymentTypeDetailUsingGET = (
  params: { [key: string]: never },
  { unionId } = {
    unionId: string
  }
) =>
  axios.request<Result<PaymentTypeDetailResponse>, AxiosResponse<Result<PaymentTypeDetailResponse>>>({
    url: `/v1/admin/payment-types/${unionId}`,
    method: "get",
    params: {},
    data: {}
  });

// 编辑付款类型
export const editPaymentTypeUsingPUT = (
  params: PaymentTypeRequest,
  { unionId } = {
    unionId: string
  }
) =>
  axios.request<Result, AxiosResponse<Result>>({
    url: `/v1/admin/payment-types/${unionId}`,
    method: "put",
    params: {},
    data: params
  });
